---
_rule:
  domain: EC
  scope: lot
  kind: consistency
  severity: ERROR

logic: national_codelist_dependency

params:
  target: award_criterion_type_lot
  codelist_file: "award-criterion-type.no.yaml"
  list_name: "award-criterion-type"
  _description: 
    nob: >-
      Hvis tildelingskriterier er oppgitt, kreves beskrivelse av
      på hvilken måte klima- og miljøbestemmelsene i norsk
      anskaffelsesregelverk etterleves.
    nob_verify: false
    nno: >-
      I fall tildelingskriterium er oppgitt, krevst beskriving av
      på kva for ein måte klima- og miljøreglane i norsk
      anskaffingsregelverk blir etterlevde.
    nno_verify: false
    eng: >-
      In the event that award criteria are provided, it is required
      to inform in what way the procurement complies with the climate-
      and environmental considerations in the Norwegian public procurement
      regulations.
    eng_verify: false
  
  
