---
_rule: 
  domain: LT
  scope: global
  kind: whitelist

logic: any_of

params: 
  override_if:
    legal_basis_noid: EXEMPT
  
  mandatory: true
  
  _dependencies:
    fields:
      legal_basis_noid: "legal_basis_noid"
      legal_basis_descriptions:
        - legal_basis_description: "legal_basis_noid_description_nor"
          lang: "nor"
        - legal_basis_description: "legal_basis_noid_description_eng"
          lang: "eng"
    external_data:
      - file: "rules/legal_basis_procedure.yaml"
        id: "lb_registry"

  base_list: buyer-legal-type
  base_modification: leaves-only
  target: buyer_legal_type
  _description: 
    nob: >-
      Spesifikke juridiske typer er tillatt. Overordnede kategorier
      er for generelle. Detaljnivået spiller rolle for spesifisering
      av terskelverdier.
    nob_verify: false
    nno: >-
      Spesifikke juridiske typar er tillatne. Overordna kategoriar er
      for generelle. Detaljnivået speler rolle for spesifisering av
      terskelverdiar.
    nno_verify: false
    eng: >-
      Specific legal types are allowed. Overarching categories are
      too generic. The detailed types are significant for specifying
      threshold values.
    eng_verify: false
